info: |-
    Parallel coordinates plot that allows brushing, and moving the axes.

    Parameters
    "color_by" is the name of the column that is used to generate the color palette.
    If not specified explicitly, the template uses the first column of the input data.

    "domain" will be used to set the domain of the color palette.
    Because it uses the D3 domain function, it can be a vector of 2 elements c(min, max)
    or 3 c(min, middle, max).

    "colors" is a color palette. It can be specified using names c("red", "blue", "green") or hex colors c("#FFFF33", "#000")

original_url: http://syntagmatic.github.com/parallel-coordinates/examples/brushing.html

demo: |-
    cars <- read_ractive_csv("par_coords", "original_data.csv")
    clickme(cars, "par_coords", params = list(color_by = "economy"))

data_names:
    required:
    optional:

params:
    title: "PCP"
    width: 1024
    height: 700
    color_by:
    domain:
    colors:
    padding:
        top: 24
        right: 0
        bottom: 12
        left: 200

scripts:
    - d3.v3.js
    - d3.parcoords.js

styles:
    - d3.parcoords.css
    - style.css

require_packages:
    - rjson

require_server: yes
