info: |
    Zoomable phylogenetic tree viewer that allows interactive display of large trees.

    clickme allows three types of input containing an ultrametric Newick tree (polytomies as branch length zero):
    1) A path to a file containing a tree in string form

        library(clickme)
        mammals_path <- system.file(file.path("examples", "one_zoom", "data", "mammals.tree"), package="clickme")
        clickme(mammals_path, "one_zoom")

    2) A tree in string form

        mammals_path <- system.file(file.path("examples", "one_zoom", "data", "mammals.tree"), package="clickme")
        mammals <- scan(mammals_path, "character")
        clickme(mammals, "one_zoom")

    3) An object of class phylo

        mammals_path <- system.file(file.path("examples", "one_zoom", "data", "mammals.tree"), package="clickme")
        library(ape)
        mammals <- read.tree(mammals_path)
        clickme(mammals, "one_zoom")

    Also, try a simpler example:

        clickme("(((A:4.2,B:4.2):3.1,C:7.3):6.3,D:13.6);", "one_zoom")


valid_names:

name_comments: |

scripts:
    - OZ_W_1/User_options_13.js
    - OZ_W_1/JScode_W_10.js
    - OZ_W_1/mammals_soption.js

styles:

default_parameters: {

}

require_packages:
    - ape

require_server: no

original_url: http://www.onezoom.org/mammals.htm

demo: |
    mammals_path <- system.file(file.path("examples", "one_zoom", "data", "mammals.tree"), package="clickme")
    clickme(mammals_path, "one_zoom")

